project:
  type: website

website:
  title: "temp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - file: matomo-analytics.html
